sudo: false
language: node_js
cache:
  directories:
    - node_modules
node_js:
  - '0.12'
  - v4
  - stable
after_success:
  - 'travis-after-all && npm run semantic-release'
env:
  global:
    - secure: aLO9PSCmHhUHjPeCcvMvYZnfG/rxCT7tJIWvnoy5r5XOAQGukTuENTWDpZCxrm3aNrPL2MgWPtvOEz4WBEQ6SEPi/ock6S8JlVMGnEtaLi3gd4dF3LlI+pqA1AuKaRYvpa74n9YRmBVbfQftcakC/kxpRXgipcZ2xwEUzKU5duoDgLT9bD8+00rb0ROoi92xy43G+CSLT+uoxCfB0OD7LwkSSpzT4J/b4JT0/aC2WFXkxNabrQDDH8/v0/Md+B3sIjGer3N96AUVqmJwbl6/sqURevTUFLyRzd+TNoFA5/RrM++hxXbKdabwqRw13Wjq9DAlbhujlXnDGa6jlohuhPqSqvUH7GGCUO/Aj6VLEoD1XAoj6FGVDDghfsjWoPqqdvNn4KgZhR5UJrHrb87A28e9Fb9g6+EyO57fsZwCdf252yW1k9+6PwEdt3LtNScIr14u8WTSWSeHRM01yy4kWNSlVJIJlwO8J3xPJQtJCBGYd9zpLZx8ZDVkYVetPAalj/iwuGtkB6XS/LWYtbS2mBLoyBHluSCv4It0rINdbjptD47JnARYefkM2oLiKoUCBj0kdYnDrJc/hN2gHERu22RcyuTlhPOVGvruwszbDNOHtLbi6WQIgZMRv3iMwokrvlcmHIPQwNdVesewnxOugardH8cU9KPQu/92F9TBrfc=
    - secure: gtu3w+7airy01bdDbmlRT3CboGLW7uCQMYqQVgbALnO36P4K7wCfsneTf8ZJ1zvvtS8Akdl45XSb4nR3eC/fJHTsKVfgWvUsqJOtVM/Vhst0ysw241kKd4o0XFY3OsySemJH+vdSt7ATZPN/0kaXekuxgpVbfeUiHgJVqVGiQ5ERa6I6ibpuWbzNMIAhpjC0SSmx51zsjtSKz7sCj5tk2b2WcpGodCx59MUqMfewM8Hw1CR9maD5an7SWKunBZnpsQEHpSWUSl6CEB3ffWXxuTcIZIYRwuT/6qnGTbWRSaQuu4XKcSo7WtZoMJHIqcg75KhSagog31nZBKfRf2uekpzQgLlALHT7IZUGLZ4ExenuBSiE7xgPYnOqAuE3FUyuDJAX7XVFbhjHkLwSeBVlvI72ELM4ljJwO6X5+8E0gFjmQoBAKIXaSynCDao2/MNzBHXzCU1u5uUj/tfW+7JgEptzXjIkiA315bl+7/soAIqoIvrUxx11fUc9FdWtlGnQrTKjgd+4EsAD+D7p6T3e4eaWNg7iX0Atz1TTtSVkZLZ7VTKDbjeYf4pWCk3PCmxSD6yDX65x94MHJrog/jGYsz1TAhk/utBRT+pEixsyXymerY/UkD3TDYq6TiAfFZSakEreT/klAu0lfccyHpBv9H29fhHDs89qgd52YY2Cdmo=
